export const ACCOUNT_FETCH_BEGIN = 'ACCOUNT_FETCH_BEGIN';
export const ACCOUNT_FETCH_SUCCESS = 'ACCOUNT_FETCH_SUCCESS';
export const ACCOUNT_FETCH_FAILURE = 'ACCOUNT_FETCH_FAILURE';

export const ACCOUNT_LOGOUT_BEGIN = 'ACCOUNT_LOGOUT_BEGIN';
export const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';
export const ACCOUNT_LOGOUT_FAILURE = 'ACCOUNT_LOGOUT_FAILURE';

export const ACCOUNT_AUTHENTICATED_SUCCESS = 'ACCOUNT_AUTHENTICATED_SUCCESS';
export const ACCOUNT_AUTHENTICATED_FAILURE = 'ACCOUNT_AUTHENTICATED_FAILURE';