export const PUBLIC_DRAGONS_FETCH_BEGIN = 'PUBLIC_DRAGONS_FETCH_BEGIN';
export const PUBLIC_DRAGONS_FETCH_SUCCESS = 'PUBLIC_DRAGONS_FETCH_SUCCESS';
export const PUBLIC_DRAGONS_FETCH_FAILURE = 'PUBLIC_DRAGONS_FETCH_FAILURE';